name: .NET

on :
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore VO.Essentials.sln
    - name: Build
      run: dotnet build VO.Essentials.sln --no-restore
    - name: Test
      run: dotnet test VO.Essentials.sln --no-build --verbosity normal
    - name: Publish to Nuget 
      run: dotnet nuget push "**/src/nuget/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n 
